sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

os:
  - linux
  - osx

env:
  matrix:
    # node
    - RUNTIME="node" RVERSION="0.10"
    - RUNTIME="node" RVERSION="0.12"
    - RUNTIME="node" RVERSION="4"
    - RUNTIME="node" RVERSION="6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - cmake
      - cmake-data

before_install:
  # set CXX to g++-4.9 on linux
  - | 
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      export CC=gcc-4.9
      export CXX=g++-4.9
    fi

  # install node
  - export NODE_VERSION=$RVERSION
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm && source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install npm -g

  # update path
  - PATH=$PATH:`pwd`/node_modules/.bin

  # print some info
  - uname -a
  - npm --version
  - node --version
  - node -p 'process.platform + "@" + process.arch'
  - $CXX --version

  # install recent cmake for osx
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      travis_retry wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Darwin-x86_64.tar.gz
      tar -xzf cmake-3.4.3-Darwin-x86_64.tar.gz
      export PATH=$PWD/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin:$PATH
    fi

  # cleanup npm progress
  - npm config set progress false
  - npm config set spin false

install:
  # build
  - npm install

script:
  # test
  - npm test
