environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

os: Visual Studio 2017
platform: x64

cache:
  - node_modules

skip_commits:
  files:
    - .travis.yml

install:
  - git submodule update --init --recursive
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - cmake --version
  - npm test

build: off
